#!/bin/bash
terraforming alb 
terraforming asg 
terraforming cwa 
terraforming dbpg
terraforming dbsg
terraforming dbsn
terraforming ec2 
terraforming ecc 
terraforming ecsn
terraforming efs 
terraforming eip 
terraforming elb 
terraforming help
terraforming iamg
terraforming iamgm
terraforming iamgp
terraforming iamip
terraforming iamp 
terraforming iampa
terraforming iamr 
terraforming iamrp
terraforming iamu 
terraforming iamup
terraforming igw  
terraforming kmsa 
terraforming kmsk 
terraforming lc   
terraforming nacl 
terraforming nat  
terraforming nif  
terraforming r53r 
terraforming r53z 
terraforming rds  
terraforming rs   
terraforming rt   
terraforming rta  
terraforming s3   
terraforming sg   
terraforming sn   
terraforming snss 
terraforming snst 
terraforming sqs  
terraforming vgw  
terraforming vpc  
