---
- name: Deploy developer environment
  vars:
    docker_opts: []
    docker_env: []
    #      HTTP_PROXY: "http://127.0.0.1:8080"
    #  HTTPS_PROXY: "https://127.0.0.1:8080"

  hosts: "{{ hostsvar | default('all') }}"
  gather_facts: true
  remote_user: root
  tasks:
    - name: setup proxy
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy=http://proxy.cc.absee.azt.cloud.allianz:8080'
    - name: Include system based tasks
      include: tasks/main.yml
